### ISSUE TITLE
Running the demo fails on Windows

### ISSUE THREAD

**Issue by abeyahmad** [angular/angular-electron#4]
> @angular2/electron@1.0.0 clean C:\users\ibrah\projects\angular-electron
> rm -rf dist

'rm' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "run" "clean"
npm ERR! node v4.2.4
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! @angular2/electron@1.0.0 clean: `rm -rf dist`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @angular2/electron@1.0.0 clean script 'rm -rf dist'.
npm ERR! This is most likely a problem with the @angular2/electron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rm -rf dist
npm ERR! You can get their info via:
npm ERR!     npm owner ls @angular2/electron
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\users\ibrah\projects\angular-electron\npm-debug.log

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "run" "build"
npm ERR! node v4.2.4
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! @angular2/electron@1.0.0 build: `npm run clean && tsc`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @angular2/electron@1.0.0 build script 'npm run clean && tsc'.
npm ERR! This is most likely a problem with the @angular2/electron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run clean && tsc
npm ERR! You can get their info via:
npm ERR!     npm owner ls @angular2/electron
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\users\ibrah\projects\angular-electron\npm-debug.log

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "run" "demo"
npm ERR! node v4.2.4
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! @angular2/electron@1.0.0 demo: `npm run build && npm run build_demo && electron ./demo`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @angular2/electron@1.0.0 demo script 'npm run build && npm run build_demo && electron ./demo'.
npm ERR! This is most likely a problem with the @angular2/electron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build && npm run build_demo && electron ./demo
npm ERR! You can get their info via:
npm ERR!     npm owner ls @angular2/electron
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\users\ibrah\projects\angular-electron\npm-debug.log
PS C:\users\ibrah\projects\angular-electron> npm run demo

**Comment by dsebastien** [comment]
I've sent a PR to fix that

**Comment by abeyahmad** [comment]
Still fails
