### ISSUE TITLE
Cannot Install, Run

### ISSUE THREAD

**Issue by leifwells** [angular/angular-electron#8]
I've followed your instructions on the README but have not been able to get the demo to run.

I believe that you may have some modules installed globally that you have not mentioned. 
- I installed `typings` globally, but your `package.json` scripts `build` and `build_demo` requires `tsc` to be installed.
- `electron ./demo` fails via the `demo` script as well as via command line.
- Running `node_modules/electron-prebuilt/dist/Electron.app/Contents/MacOS/Electron ./demo` fails with `Error: Cannot find module '/Users/leifwells/electron/angular-electron-master/demo'` (which makes no sense because that is the correct path)

When possible, help me assist you. I'd like to see this project be successful.

Thanks/

**Comment by mcgraphix** [comment]
I was able to get npm install to work by changing the package.json to:

```
"dependencies": {
    "angular2": "^2.0.0-beta.11",
    "es6-promise": "^3.1.2",
    "es6-shim": "^0.35.0",
    "parse5": "^1.5.1",
    "reflect-metadata": "0.1.2",
    "rxjs": "5.0.0-beta.2",
    "zone.js": "^0.6.4"
  }
```

However, npm start fails with this error message:
src/platform/electron_message_bus.ts(50,16): error TS2339: Property 'onTurnDone' does not exist on type 'NgZone'.
src/platform/electron_renderer_common.ts(39,39): error TS2307: Cannot find module 'angular2/src/router/browser_platform_location'.

The second error looks like a path issue as that file exists at 'angular2/src/router**_/location_**/browser_platform_location'.
